// Ordlistan för Agenter. Egen svensk lista — ligger på backend så att
// servern kan dela ut bräden, och frontend hämtar den för lokalt läge.

export const WORDS = [
  // Djur
  "HUND","KATT","HÄST","ELEFANT","ORM","ÖRN","VARG","BJÖRN","RÄV","ÄLG",
  "MYRA","SPINDEL","HAJ","VAL","DELFIN","KRÅKA","UGGLA","GRODA","IGELKOTT","KANIN",
  "MUS","RÅTTA","FLADDERMUS","KROKODIL","KAMEL","LEJON","TIGER","PINGVIN","SÄL","MYGGA",
  "FJÄRIL","SNIGEL","KRABBA","BLÄCKFISK","PAPEGOJA","DUVA","SVAN","TUPP","GRIS","GET",
  "HÖNA","LAX","GÄDDA","MÅS","APA","GIRAFF","NOSHÖRNING","EKORRE","BÄVER","MYRSLOK",
  // Mat och dryck
  "BRÖD","OST","SMÖR","ÄGG","MJÖLK","KAFFE","SOCKER","SALT","PEPPAR","CHOKLAD",
  "GLASS","KAKA","TÅRTA","KORV","SOPPA","SALLAD","PIZZA","PASTA","POTATIS","MOROT",
  "LÖK","TOMAT","GURKA","ÄPPLE","BANAN","APELSIN","CITRON","DRUVA","JORDGUBBE","HALLON",
  "BLÅBÄR","SVAMP","HONUNG","SENAP","VIN","JUICE","MJÖL","KANEL","SILL","RÄKA",
  "KÖTTBULLE","PANNKAKA","KNÄCKEBRÖD","GRÖT","SYLT","PEPPARKAKA","MUSSLA","NÖT","KRYDDA","DEG",
  // Platser
  "SKOLA","SJUKHUS","KYRKA","SLOTT","FYR","HAMN","STATION","FLYGPLATS","BIBLIOTEK","MUSEUM",
  "TEATER","BIOGRAF","RESTAURANG","HOTELL","MARKNAD","TORG","PARK","STRAND","ÖKEN","DJUNGEL",
  "BERG","DAL","GROTTA","SKOG","ÄNG","SJÖ","FLOD","VATTENFALL","VULKAN","GLACIÄR",
  "RYMDEN","MÅNEN","PLANET","STJÄRNA","HIMMEL","NORDPOLEN","EGYPTEN","PARIS","LONDON","ROM",
  "TOKYO","KINA","INDIEN","ISLAND","GÖTEBORG","STOCKHOLM","ALPERNA","LAPPLAND","VENEDIG","PYRAMID",
  // Roller och figurer
  "LÄKARE","POLIS","BRANDMAN","LÄRARE","PILOT","KOCK","BAGARE","SNICKARE","MÅLARE","MUSIKER",
  "SÅNGARE","DANSARE","SKÅDESPELARE","FÖRFATTARE","DOMARE","ADVOKAT","PRÄST","SOLDAT","SPION","TJUV",
  "PIRAT","RIDDARE","KUNG","DROTTNING","PRINSESSA","JÄTTE","TROLL","HÄXA","VAMPYR","SPÖKE",
  "ROBOT","ÄNGEL","CLOWN","TROLLKARL","ASTRONAUT","DYKARE","JÄGARE","FISKARE","BONDE","VAKT",
  "MEKANIKER","FRISÖR","TANDLÄKARE","BREVBÄRARE","VIKING","NINJA","DETEKTIV","GRANNE","TVILLING","KOMPIS",
  // Saker i hemmet
  "BORD","STOL","SÄNG","SOFFA","LAMPA","SPEGEL","KLOCKA","NYCKEL","LÅS","DÖRR",
  "FÖNSTER","TAK","GOLV","TRAPPA","STEGE","HAMMARE","SPIK","SÅG","SKRUV","YXA",
  "KNIV","GAFFEL","SKED","TALLRIK","GLAS","FLASKA","BURK","KORG","PÅSE","VÄSKA",
  "PLÅNBOK","MYNT","SEDEL","RING","HALSBAND","KRONA","KAMERA","TELEFON","DATOR","SKÄRM",
  "RADIO","GITARR","PIANO","TRUMMA","FIOL","FLÖJT","BOK","PENNA","PAPPER","SAX",
  "LIM","BOLL","BALLONG","DRAKE","TÄRNING","PUSSEL","DOCKA","NALLE","PARAPLY","HATT",
  "SKO","STRUMPA","HANDSKE","HALSDUK","JACKA","KJOL","SLIPS","KNAPP","NÅL","TRÅD",
  "TVÅL","TANDBORSTE","HANDDUK","KUDDE","FILT","MATTA","GARDIN","HYLLA","LÅDA","KISTA",
  "TUNNA","HINK","SPADE","KRATTA","SLANG","REP","KEDJA","ANKARE","SEGEL","ÅRA",
  "FALLSKÄRM","KIKARE","MIKROSKOP","TELESKOP","KOMPASS","KARTA","GLOB","TERMOMETER","LINJAL","BATTERI",
  "MAGNET","FJÄDER","KAM","BORSTE","LJUS","STÄMPEL","FRIMÄRKE","PORTFÖLJ","MIKROFON","HÖRLURAR",
  // Fordon
  "BIL","BUSS","TÅG","SPÅRVAGN","CYKEL","MOTORCYKEL","LASTBIL","TRAKTOR","BÅT","FÄRJA",
  "UBÅT","FLYGPLAN","HELIKOPTER","RAKET","SKATEBOARD","SKIDOR","SKRIDSKO","SLÄDE","VAGN","TAXI",
  "AMBULANS","KANOT","SEGELBÅT","HISS","RULLTRAPPA",
  // Natur och väder
  "REGN","SNÖ","IS","DIMMA","STORM","ÅSKA","BLIXT","VIND","SOL","MOLN",
  "REGNBÅGE","HAGEL","FROST","VÅG","ELD","RÖK","ASKA","SAND","STEN","LERA",
  "TRÄD","BLAD","BLOMMA","ROS","GRÄS","MOSSA","ROT","FRÖ","KOTTE","EK",
  "TALL","BJÖRK","KAKTUS","PALM","SKUGGA","HAV","VIK","KLIPPA","GRUS","LAVA",
  // Kropp
  "HJÄRTA","HJÄRNA","ÖGA","ÖRA","NÄSA","MUN","TAND","TUNGA","HAND","FOT",
  "FINGER","ARM","RYGG","AXEL","HÅR","SKÄGG","BLOD","SKELETT","PULS","ANDNING",
  // Sport och spel
  "FOTBOLL","HOCKEY","TENNIS","GOLF","BOXNING","SCHACK","POKER","BOWLING","HANDBOLL","BASKET",
  "LÖPNING","SIMNING","BÅGSKYTTE","RIDNING","KLÄTTRING","MÅL","MEDALJ","POKAL","LAG","MATCH",
  // Byggt och samhälle
  "BRO","TUNNEL","VÄG","GATA","TORN","MUR","STAKET","GRIND","BRUNN","KÄLLARE",
  "GARAGE","STUGA","TÄLT","IGLOO","KVARN","FABRIK","GRUVA","BANK","APOTEK","LADA",
  "PLATTFORM","PERRONG","BALKONG","SKORSTEN","VINDSKUPA",
  // Abstrakt och övrigt
  "TID","DRÖM","MINNE","LJUD","TYSTNAD","HEMLIGHET","LÖGN","SANNING","KÄRLEK","TUR",
  "ÖDE","MAGI","KRAFT","ENERGI","VIRUS","FEBER","PLÅSTER","MEDICIN","GIPS","MÖRKER",
  "JULGRAN","TOMTE","PÅSK","MIDSOMMAR","FEST","BRÖLLOP","FÖDELSEDAG","PRESENT","KALAS","SEMESTER",
  "KÖ","BILJETT","KVITTO","ALARM","LÖSENORD","SIGNAL","KOD","BEVIS","SPÅR","UPPDRAG"
];

export default WORDS;
